### ISSUE TITLE
Footer - quick links

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#1]
1. need to only allow the quick links to show 3 across so the info still sits to the right.

2. update the hover colour on the quick links to the colour of the circle in the footer
3. 
![Screenshot 2023-07-03 14 38 19](https://github.com/markendley/soda/assets/90736622/03069bde-81f2-40ee-a6fa-11750c4b10ba)

**Comment by Treadstudio** [comment]
on mobile...

1. need spacing between the rows
2. all buttons needs to be the same width (e.g. asset is not as wide as inventory)
3. 
![8](https://github.com/markendley/soda/assets/90736622/4170450b-1951-4343-bc05-2061da1c0a2e)

**Comment by markendley** [comment]
fixed
