### ISSUE TITLE
Feature module - mobile 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#10]
sub text need to come across 

![5](https://github.com/markendley/soda/assets/90736622/43009002-0bc0-4436-be55-8443fbfef8b6)

needs to be more space between the callouts (too tight currently) 

![4](https://github.com/markendley/soda/assets/90736622/7a5641e3-3766-4f23-aa5e-8f96250858f1)

**Comment by Treadstudio** [comment]
issue with the text sitting in the background as well - sitting too low 

![6](https://github.com/markendley/soda/assets/90736622/9993ed23-e058-4d89-9840-dc2b4f4376cd)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
heaps better.

i think we drop the size of the purple heading down a little (its at 3em), the heading about is at 2.65em. Let's bring it down to 2.65 and see how that looks
