### ISSUE TITLE
mobile - header images

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#11]
can we extend them down a little more?

![3](https://github.com/markendley/soda/assets/90736622/1f49da44-3281-4819-bbee-87e823049073)

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
think something has gone amiss.

I wanted the white to stay where it was but the image to come down a little further behind it.

this is what i'm now getting

![11](https://github.com/markendley/soda/assets/90736622/064dfd74-e45a-42f0-a44e-cf4338e004cc)
![10](https://github.com/markendley/soda/assets/90736622/153a77c8-8d43-45df-ad47-b79f6e4a41a9)

**Comment by markendley** [comment]
ok try now

**Comment by Treadstudio** [comment]
i'm not seeing that update. still looks the same

**Comment by Treadstudio** [comment]
I can see it in browser stack on a 14 running IOS 16.3 but not on my actual iphone (running IOS 15.1)

ok so it's an IOS 15 issue. Seeing the same problem in browserstack on IOS15.x on a iphone 13

**Comment by markendley** [comment]
fixed
