### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#13]
side scroll needs adjustment. on large break point it's not locking in place so i scroll past.

on small desktop and mobile it's sitting too high in screen. Can we get it to lock middle?

![7](https://github.com/markendley/soda/assets/90736622/9b63d8f8-f91b-4a75-aabb-59b41c4c4dea)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
heaps better - just have a weird amount of line after the last point. Can we get rid of most of it? 


![Screenshot 2023-07-03 22 07 44](https://github.com/markendley/soda/assets/90736622/532c34f5-4aea-4712-abe5-cf3af5b0bbc3)

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
not seeing this update
