### ISSUE TITLE
features module - text sizes desktop to mobile 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#15]
can you check the scaling on the heading text + the purple heading text.

The main section heading looks smaller on desktop than the purple but it is bigger on mobile?

Either way i think we need to adjust across devices.

**Comment by markendley** [comment]
ok, i had to  fix a few heading sizes

**Comment by Treadstudio** [comment]
heaps better.

i think we drop the size of the purple heading down a little (its at 3em), the heading about is at 2.65em. Let's bring it down to 2.65 and see how that looks

**Comment by markendley** [comment]
done
