### ISSUE TITLE
DNS Logins

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#17]
https://www.godaddy.com/en-au

Login: jord.edwards@outlook.com
Password: W&lter8oy

**Comment by markendley** [comment]
I gotta get a 2FA code to get in

Right now, can you tell me what the domain is gonna be?

Am I simply just uploading the files, or would I be doing any DNS changes (Eg. changing nameservers?)

**Comment by Treadstudio** [comment]
DNS lives here (just doing an a record update)

Hosting i'm setting up now and will laod in (domain is sodacapital.com.au)

**Comment by markendley** [comment]
done
