### ISSUE TITLE
Inventory Finance Page - spacing between standout and feature module

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#2]
needs spacing between the edge of the purple and the image - ref: proof/design file 

![Screenshot 2023-07-03 14 32 57](https://github.com/markendley/soda/assets/90736622/e2d6a1cc-7e0e-46ea-a649-fb6cd3745d5b)

**Comment by Treadstudio** [comment]
same issue on the asset finance page

![Screenshot 2023-07-03 19 57 14](https://github.com/markendley/soda/assets/90736622/a1c9b833-f6e3-4ef2-9856-5925923b83f8)

**Comment by markendley** [comment]
fixed
