### ISSUE TITLE
Apply now form - mobile

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#20]
losing placeholder text on mobile? 

What's better....reduce the length of the text or make a size adjustment?

![12](https://github.com/markendley/soda/assets/90736622/feb437b3-a019-407e-be64-432acbea2173)

**Comment by markendley** [comment]
Already made the size adjustments, but you can remove a couple of words.

<img width="585" alt="Screenshot 2023-07-04 at 12 37 02 pm" src="https://github.com/markendley/soda/assets/6570606/26db4a6c-4925-402b-96cf-1a37042fea11">

**Comment by Treadstudio** [comment]
thanks. in the your screenshot - notice how the purples is extending out...can we amend please?

**Comment by markendley** [comment]
good eye

fixed
