### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#24]

**Comment by Treadstudio** [comment]
Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page. 


<script async src="https://www.googletagmanager.com/gtag/js?id=G-XZ0KXFMNSJ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XZ0KXFMNSJ');
</script>

**Comment by markendley** [comment]
done
