### ISSUE TITLE
feature pages

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#4]
need to lock the height regardless of the difference in text so both are sitting flush

![Screenshot 2023-07-03 14 08 30](https://github.com/markendley/soda/assets/90736622/a3eeadfc-0936-4c0e-b60f-70d2c0fe0fc7)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
can we align the buttons as well please? - asset finance is sitting up slightly

**Comment by markendley** [comment]
certainly
